---
- name: Install APACHE2 On Web Servers
  hosts: ubu
  become: yes

  tasks:
  - name: Ensure System Updated
    apt:
      update_cache: yes

  - name: Ensure Apache HTTP Installed
    apt:
      name: apache2
      state: present

  - name: Ensure Apache HTTP Started
    service:
      name: apache2
      state: started

  - name: Ensure Apache HTTP Enabled
    service:
      name: apache2
      enabled: yes
...
