---
- name: Install Apache HTTPD - web servers
  hosts: all
  become: yes

  tasks:
  - name: Ensure System Packages Updated
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache Installed Centos
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Ensure Apache Installed Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache Started Centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Ensure Apache Started Ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
...